Digiticket.cms/Models/Supplier/Supplier.cs
using Services.Models.Responses.Lib;
using Services.Models.Responses.Supplier;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DigiticketCMS.Models.Supplier
{
    public class Supplier : BaseViewModel
    {

    }

    public class SupplierGetByPageViewModel
    {
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
    }

    public class SupplierCreateViewModel
    {
        [Required]
        public string Name { get; set; }
        //[Required]
        //public string Code { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string ContactName { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Hotline { get; set; }
        [Required]
        public string BookingEmail { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyRepresentative { get; set; }
    }

    public class SupplierUpdateBaseInfoViewModel
    {
        [Required]
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string ContactName { get; set; }
        [Required]
        public string Phone { get; set; }
        [Required]
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyRepresentative { get; set; }
    }

    public class SupplierUpdateTenantViewModel
    {
        [Required]
        public string Id { get; set; }
        public string Name { get; set; }
        public int TenantId { get; set; }
        public string TenantCode { get; set; }
    }

    public class SupplierUpdateBookingInfoViewModel
    {
        [Required]
        public string Id { get; set; }
        [Required]
        public string Hotline { get; set; }
        [Required]
        public string BookingEmail { get; set; }
    }

    public class SupplierCreateBankViewModel
    {
        [Required]
        public string SupplierId { get; set; }
        public int? Id { get; set; }
        [Required]
        public string AccountName { get; set; }
        [Required]
        public string AccountNo { get; set; }
        [Required]
        public string BankName { get; set; }
        [Required]
        public string BranchName { get; set; }
    }

    public class SupplierDeleteBankViewModel
    {
        [Required]
        public string Id { get; set; }
        [Required]
        public string SupplierId { get; set; }
    }

    public class SupplierGetFromIdViewToHtmlViewModel
    {
        public string Id { get; set; }
        public int TenantId { get; set; }
        public string TenantCode { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Title { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public string BookingEmail { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyRepresentative { get; set; }
        public int TotalRows { get; set; }
        public int Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public DateTime LastEditedDate { get; set; }
        public int LastEditedBy { get; set; }
        public string LastEditedByName { get; set; }
        public ProfileData ProfileData { get; set; }
        public string LookingFor { get; set; }
    }
    
    public class SupplierViewModel
    {
        public List<SubCategoryResponse> Categories { get; set; }
        public List<LibDestinationResponse> Destinations { get; set; }
        public string Id { get; set; }
        public int TenantId { get; set; }
        public string TenantCode { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Title { get; set; }
        public string ContactName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Hotline { get; set; }
        public string BookingEmail { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyTaxCode { get; set; }
        public string CompanyRepresentative { get; set; }
        public int TotalRows { get; set; }
        public int Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public DateTime LastEditedDate { get; set; }
        public int LastEditedBy { get; set; }
        public string LastEditedByName { get; set; }
        public ProfileData ProfileData { get; set; }
        public string LookingFor { get; set; }
    }
}

Digiticket.cms/Controllers/SupplierController.cs
using AutoMapper;
using DigiticketCMS.Helpers;
using DigiticketCMS.Models;
using DigiticketCMS.Models.Supplier;
using DigiticketCMS.Services.Models;
using Infrastructure.Config;
using Infrastructure.Extensions;
using Services.Implement;
using Services.Interfaces;
using Services.Models.Requests.Supplier;
using Services.Models.Responses.Supplier;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace DigiticketCMS.Controllers
{
    [Authorize]
    public class SupplierController : BaseController
    {
        #region constructor
        private ISupplierServices _supplierServices;
        private ILibServices _libServices;
        public SupplierController(ISupplierServices supplierServices,
                                 ILibServices libServices)
        {
            _supplierServices = supplierServices;
            _libServices = libServices;
        }
        #endregion

        #region get by page
        public ActionResult Supplier()
        {
            if (User.CheckPermission(Permission.Suppliers))
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult SupplierGetByPage(Supplier model)
        {
            if (User.CheckPermission(Permission.SuppliersView))
            {
                var request = new SupplierGetByPageRequest()
                {
                    PageIndex = model.page,
                    PageSize = model.perpage,
                    FieldName = model.field,
                    Orderby = model.sort,
                    Keyword = string.IsNullOrEmpty(model.key) ? "" : model.key
                };
                var result = _supplierServices.GetByPage(request, User.Identity.GetClaims("token"));
                if (result.IsOK())
                {
                    long totalItems = result.Data.Total;
                    var totalPages = Math.Ceiling((double)totalItems / model.perpage);
                    return Json(new JsonDataTable
                    {
                        meta = new PagingInfo
                        {
                            page = model.page,
                            pages = (long)totalPages,
                            perpage = model.perpage,
                            total = totalItems
                        },
                        data = result.Data.Result
                    }, JsonRequestBehavior.AllowGet);
                }
                else if (result.Code == 401)
                {
                    Response.Cookies[SystemConfig.System_AuthCookieName].Value = string.Empty;
                    Response.Cookies[SystemConfig.System_AuthCookieName].Expires = DateTime.Now.AddMonths(-1);
                    return Json(new
                    {
                        page = "login page"
                    }, JsonRequestBehavior.AllowGet);
                }
                return Json(new JsonDataTable
                {
                    meta = new PagingInfo()
                    {
                        page = model.page,
                        perpage = model.perpage,
                    },
                    data = new List<SupplierResponse>()
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonDataTable
            {
                meta = null,
                data = new List<SupplierResponse>()
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region add
        [HttpGet]
        public ActionResult Add()
        {
            if (User.CheckPermission(Permission.SuppliersAdd))
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public JsonResult Add(SupplierCreateViewModel model)
        {
            if (User.CheckPermission(Permission.SuppliersAdd))
            {
                if (ModelState.IsValid)
                {
                    var request = Mapper.Map<SupplierRequest>(model);
                    var result = _supplierServices.Add(request, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        return Json(new JsonClientResult
                        {
                            Success = true,
                            CallBack = $"CreateOrUpdate.onRendAfterAdd(`{result.Data}`);"
                        }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new JsonClientResult
                    {
                        CallBack = result.Errors.CB_UpdateErrorResult()
                    }, JsonRequestBehavior.AllowGet);
                }
                return Json(new JsonClientResult
                {
                    Success = false,
                    Message = GetModelStateError(),
                    CallBack = $"Common.onError('Không thêm được! Có lỗi xảy ra! {GetModelStateError()}')"
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonClientResult
            {
                Success = false,
                Message = GetModelStateError(),
                CallBack = $" swal.fire('Oops!', 'You have no permission for this action!', 'error');"
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region detail 
        [HttpGet]
        public ActionResult SupplierDetail(Guid id)
        {
            if (User.CheckPermission(Permission.Suppliers))
            {
                if (id != Guid.Empty)
                {
                    var result = _supplierServices.GetById(id, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        var model = Mapper.Map<SupplierViewModel>(result.Data);
                        model.Categories = _libServices.CategoryGetAll(User.Identity.GetClaims("token")).Data;
                        model.Destinations = _libServices.DestinationGetAll(User.Identity.GetClaims("token")).Data;
                        return View(model);
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region update tenant
        [HttpGet]
        public ActionResult SupplierUpdatenantModal(SupplierUpdateTenantViewModel model)
        {
            if (User.CheckPermission(Permission.SuppliersImportProduct))
            {
                if (ModelState.IsValid)
                {
                    var result = Mapper.Map<SupplierUpdateTenantRequest>(model);
                    return PartialView("Partial/_SupplierUpdateTenantModal", result);
                }
            }
            return View("~/Views/Shared/Error.cshtml");
        }

        [HttpPost]
        public JsonResult SupplierUpdateTenant(SupplierUpdateTenantViewModel model)
        {
            if (ModelState.IsValid)
            {
                var request = Mapper.Map<SupplierUpdateTenantRequest>(model);
                var result = _supplierServices.UpdateTenant(request, User.Identity.GetClaims("token"));
                if (result.IsOK())
                {
                    return Json(new JsonClientResult
                    {
                        CallBack = "SupplierDetail.onRendAfterGetListByTenantFromDigipost();",
                        Success = true
                    }, JsonRequestBehavior.AllowGet);
                }
                return Json(new JsonClientResult
                {
                    CallBack = result.Errors.CB_UpdateErrorResult()
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonClientResult
            {
                CallBack = $"Common.onError(`{GetModelStateError()}`);"
            }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult SuggestTenantByKey(string key = "")
        {
            var result = new List<SupplierTenantResponse>();
            if (key.CheckForKey())
            {
                var model = _supplierServices.SupplierTenantGetByKey(key, User.Identity.GetClaims("token"));
                if (model.IsOK() && model.Data != null)
                {
                    result = model.Data.ToList();
                }
            }
            return Json(new JsonClientResult
            {
                Success = true,
                Data = result
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region update base info
        public JsonResult SupplierUpdateBaseInfo(SupplierUpdateBaseInfoViewModel model)
        {
            if (User.CheckPermission(Permission.SuppliersEdit))
            {
                if (ModelState.IsValid)
                {
                    var request = Mapper.Map<SupplierRequest>(model);
                    var result = _supplierServices.UpdateBaseInfo(request, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        return Json(new JsonClientResult
                        {
                            CallBack = $"SupplierDetail.onRendAfterUpdateName(`{model.Name}`);",
                            Success = true
                        }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new JsonClientResult
                    {
                        CallBack = result.Errors.CB_UpdateErrorResult()
                    }, JsonRequestBehavior.AllowGet);
                }
                return Json(new JsonClientResult
                {
                    CallBack = $"Common.onError(`{GetModelStateError()}`);"
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonClientResult
            {
                CallBack = $"Common.onError(`You do not have permission`);"

Digiticket.cms/Views/Supplier/Partial/_ListSupplierGetByKeySuggest.cshtml
@using Services.Models.Responses.Supplier;
@using Infrastructure.Extensions;
@model List<SupplierTenantResponse>

<ul class="list-suggest mt-2" style="padding-inline-start:1rem">
    @if (!Model.IsNullOrEmpty())
    {
        foreach (var item in Model)
        {
            <li class="pointer mt-2 template" data-id="@item.TenantId" data-code="@item.Code">@item.Name</li>
        }
    }
    else
    {
        <li class="mt-2">Không có kết quả</li>
    }
</ul>

Digiticket.cms/Views/Supplier/Partial/_SupplierAddOrUpdateBankModal.cshtml
@using Services.Models.Requests.Supplier;
@model SupplierUpdateBankRequest

@{
    var isReadOnly = Model.Id == null;
}

@using (Html.BeginForm("SupplierCreateOrUpdateBank", "Supplier", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    @class = "validatiteUpdateBank kt-form ajax-form",
    showLoading = true,
    spellcheck = false
}))
{
    <div class="modal-header">
        <h1 class="modal-title">Update Bank</h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <input type="hidden" value="@Model.SupplierId" name="supplierId" readonly />
        @if (!isReadOnly)
        {
            <input type="hidden" value="@Model.Id" name="Id" readonly />
        }
        <div class="mb-2 position-relative">
            <div>
                <label for="accountName">Tên tài khoản</label><label class="text-red error ml-5" for="accountName"></label>
                <input class="form-control" placeholder="Nhập tên tài khoản" name="accountName" type="text" value="@Model.AccountName" />
            </div>
            <div class="mt-4">
                <label for="accountNo">Số tài khoản</label><label class="text-red error ml-5" for="accountNo"></label>
                <input class="form-control" placeholder="Nhập số tài khoản" name="accountNo" type="text" value="@Model.AccountNo" />
            </div>
            <div class="mt-4">
                <label for="bankName">Tên ngân hàng</label><label class="text-red error ml-5" for="bankName"></label>
                <input class="form-control" placeholder="Nhập ngân hàng" name="bankName" type="text" value="@Model.BankName" />
            </div>
            <div class="mt-4">
                <label for="branchName">Chi nhánh</label><label class="text-red error ml-5" for="branchName"></label>
                <input class="form-control" placeholder="Nhập chi nhánh" name="branchName" type="text" value="@Model.BranchName" />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn @(isReadOnly ? "btn-primary" : "btn-success")">Hoàn tất</button>
        @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>*@
    </div>
}

Digiticket.cms/Views/Supplier/Partial/_SupplierUpdateTenantModal.cshtml
@using Services.Models.Requests.Supplier;
@model SupplierUpdateTenantRequest

@using (Html.BeginForm("SupplierUpdateTenant", "Supplier", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    @class = "kt-form",
    @id = "FormSupplierUpdateTenant"
}))
{
    <input type="hidden" name="Id" value="@Model.Id" readonly />
    <div class="modal-header">
        <h1 class="modal-title">
            <span>Chọn Tenant</span>
        </h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <b class="text-warning">Bạn phải chọn tenant trước khi sử dụng sản phẩm từ digipost</b>
        @if (Model.Id != null)
        {
            <input type="hidden" readonly value="@Model.Id" />
        }
        <div class="alert alert-warning dp-none" role="alert">
            <div class="alert-text"></div>
        </div>
        <div class="mb-2 tags-element mt-3">
            <label>Lựa chọn tenant</label>
            @*<input class="SupplierInputGetByKey-suggest form-control" type="text" name="inputTenant" placeholder="Nhập tên tenant" />
                <div class="form-suggest-result">
                    <div class="spinner-border kt-spinner--success d-none mt-2"></div>
                </div>*@
            <label class="text-red error ml-5" for=""></label>
            <select class="form-control select-suplierTenant" name="inputTenant" id="inputTenant"></select>
            <input type="text" class="d-none" id="nameSupplier" value="@Model.Name.ToLower()" />
            <input type="text" class="d-none" id="nameTenant" name="nameTenant" />
            <input type="text" class="d-none tenantId" name="tenantId" id="tenantId" />
            <input type="text" class="d-none tenantCode" name="tenantCode" id="tenantCode" />
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Hoàn tất</button>
    </div>
}