Digiticket.cms/Models/Users/UsersViewModel.cs
using Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DigiticketCMS.Models.Users
{
    public class UsersViewModel
    {
    }

    public class WorkgroupGetUserViewModel : BaseViewModel
    {

    }

    public class UsersEditToViewModel
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public List<UserRole> Data { get; set; }
    }
    public class EditUpdateuserRolseViewModel
    {
        public long UserId { get; set; }
        public string RoleIds { get; set; }
    }
    public class WorkgroupAddUserViewModel
    {
        public List<int> Ids { get; set; }
    }
    public class GetUserRolesViewModel
    {
        public string Name { get; set; }
        public List<UserPermission> UserPermission { get; set; }
    }
    public class GetUserRolseFromClientViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }    
    }
}

Digiticket.cms/Controllers/UsersController.cs
using AutoMapper;
using DigiticketCMS.Helpers;
using DigiticketCMS.Models;
using DigiticketCMS.Models.Users;
using Infrastructure.Config;
using Infrastructure.Extensions;
using Services.Interfaces;
using Services.Models;
using Services.Models.Responses.Product;
using Services.Models.Responses.Supplier;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace DigiticketCMS.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {

        #region constructor
        private IAccountServices _accountServices;
        public UsersController(IAccountServices accountServices)
        {
            _accountServices = accountServices;
        }
        #endregion

        #region get by page
        public ActionResult Users()
        {
            if (User.CheckPermission(Permission.SysWorkGroup))
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult UsersGetByPage(WorkgroupGetUserViewModel model)
        {
            if (User.CheckPermission(Permission.SysWorkGroup))
            {
                var request = Mapper.Map<WorkgroupGetUserRequest>(model);
                request.PageIndex = model.page;
                request.PageSize = model.perpage;
                request.FieldName = model.field;
                request.Orderby = model.sort;
                if (!string.IsNullOrEmpty(model.key))
                {
                    request.Keyword = model.key;
                }
                var result = _accountServices.WorkgroupGetUser(request, User.Identity.GetClaims("token"));
                if (result.IsOK() && !result.Data.Result.IsNullOrEmpty())
                {
                    long totalItems = result.Data.Total;
                    var totalPages = Math.Ceiling((double)totalItems / model.perpage);
                    return Json(new JsonDataTable
                    {
                        success = true,
                        meta = new PagingInfo
                        {
                            page = model.page,
                            pages = (long)totalPages,
                            perpage = model.perpage,
                            total = totalItems,
                            field = model.field
                        },
                        data = result.Data.Result
                    }, JsonRequestBehavior.AllowGet);
                }
                else if (result.Code == 401)
                {
                    Response.Cookies[SystemConfig.System_AuthCookieName].Value = string.Empty;
                    Response.Cookies[SystemConfig.System_AuthCookieName].Expires = DateTime.Now.AddMonths(-1);
                    return Json(new
                    {
                        page = "login page"
                    }, JsonRequestBehavior.AllowGet);
                }
                return Json(new JsonDataTable
                {
                    meta = new PagingInfo()
                    {
                        page = model.page,
                        perpage = model.perpage,
                    },
                    data = new List<ProductResponse>()
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonDataTable
            {
                meta = null,
                data = new List<SupplierResponse>()
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Modal edit
        public ActionResult UsersAddModal()
        {
            if (User.CheckPermission(Permission.SysWorkGroup))
            {
                return PartialView("Partial/_UsersAddModal");
            }
            return PartialView("Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
            {
                Title = "You do not have permission"
            });
        }

        public ActionResult UsersEditModal(int id, string name)
        {
            if (User.CheckPermission(Permission.SysWorkGroup))
            {
                if (id != 0)
                {
                    var result = _accountServices.WorkgroupGetUserRoles(id, User.Identity.GetClaims("Token"));
                    if (result.IsOK())
                    {
                        var finalResult = new UsersEditToViewModel()
                        {
                            Id = id,
                            Name = name,
                            Data = result.Data,
                        };
                        return PartialView("Partial/_UsersEditModal", finalResult);
                    }
                    return PartialView("~/Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
                    {
                        Title = ""
                    });
                }
                return PartialView("~/Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
                {
                    Title = "Id cannot be empty!",
                });
            }
            return PartialView("Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
            {
                Title = "You do not have permission"
            });
        }
        #endregion

        #region edit
        [HttpPost]
        public JsonResult UsersEdit(EditUpdateuserRolseViewModel model)
        {
            if (ModelState.IsValid)
            {
                var request = new EditUpdateuserRolseRequest()
                {
                    RoleIds = model.RoleIds.Split('~').Select(u => Int32.Parse(u)).ToList(),
                    UserId = model.UserId
                };
                var result = _accountServices.WorkgroupUpdateUserRoles(request, User.Identity.GetClaims("token"));
                if (result.IsOK())
                {
                    return Json(new JsonClientResult()
                    {
                        Success = true,
                        CallBack = "users.onRendAfterUpdate();"
                    });
                }
                return Json(new JsonClientResult()
                {
                    CallBack = $"Common_another.showErr();"
                });
            }
            return Json(new JsonClientResult()
            {
                CallBack = $"Common_another.showErr(`{GetModelStateError()}`);"
            });
        }
        #endregion

        #region look user roles
        public ActionResult GetUserPermissionModal(GetUserRolseFromClientViewModel model)
        {
            if (model.Id != 0)
            {
                if (User.CheckPermission(Permission.SysWorkGroup))
                {
                    var result = _accountServices.WorkgroupGetUserPermissions(model.Id, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        var dataToClient = new GetUserRolesViewModel()
                        {
                            Name = model.Name,
                            UserPermission = result.Data
                        };
                        return PartialView("Partial/_GetUserPermissionModal", dataToClient);
                    }
                    return PartialView("~/Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
                    {
                        Title = result.Errors.GetResultError()
                    });
                }
                return PartialView("~/Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
                {
                    Title = "You do not have permission",
                });
            }
            return PartialView("~/Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
            {
                Title = $"Id cannot be null. Id = {model.Id}",
            });
        }
        #endregion

        #region add
        public JsonResult UsersSuggestAdd(string key = "")
        {
            if (User.CheckPermission(Permission.SysWorkGroup))
            {
                var resultToView = new List<SearchUsersResponse>();
                if (key.CheckForKey())
                {
                    var result = _accountServices.WorkgroupSearchUser(key, User.Identity.GetClaims("token"));
                    if(result.IsOK() && result.Data != null)
                    {
                        resultToView = result.Data.Result.ToList();
                    }
                }
                return Json(new JsonClientResult
                {
                    Success = true,
                    Data = resultToView
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonClientResult()
            {
                Message = "You do not have permission"
            });
        }

        [HttpPost]
        public JsonResult UsersAdd(WorkgroupAddUserViewModel model)
        {
            if (User.CheckPermission(Permission.SysWorkGroup))
            {
                var request = Mapper.Map<WorkgroupAddUserRequest>(model);
                var result = _accountServices.WorkgroupAddUser(request, User.Identity.GetClaims("token"));
                if (result.IsOK())
                {
                    return Json(new JsonClientResult()
                    {
                        Success = true,
                        CallBack = "users.onRendAfterAdd();"
                    });
                }
                return Json(new JsonClientResult()
                {
                    CallBack = $"Common_another.showErr();"
                });
            }
            return Json(new JsonClientResult()
            {
                Message = "You do not have permission"
            });
        }
        #endregion
    }
}

Digiticket.cms/Views/Users/Partial/_GetUserPermissionModal.cshtml
@using Infrastructure.Extensions;
@using DigiticketCMS.Models.Users;
@using Services.Models;
@model GetUserRolesViewModel

<div class="modal-header">
    <h1 class="modal-title">Danh sách quyền của user <span class="text-success">@Model.Name</span></h1>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="kt-portlet__body">
        <div id="UsersPermissionModalTree">
            <ul>
                @foreach (var item in Model.UserPermission)
                {
                    <li data-jstree='{"opened": true,"selected": @(item.IsSelected ? "true" : "false")}'>
                        <span>@item.Name</span>
                        @UlTree(item.SubPermission)
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

@helper UlTree(List<UserPermission> sub)
{
    if (!sub.IsNullOrEmpty())
    {
        <ul>
            @foreach (var itemSub in sub)
            {
                <li>
                    <span>@itemSub.Name</span>
                    @if (!itemSub.SubPermission.IsNullOrEmpty())
                    {
                        UlTree(itemSub.SubPermission);
                    }
                </li>
            }
        </ul>
    }
}

Digiticket.cms/Views/Users/Partial/_UsersAddModal.cshtml
@using (Html.BeginForm("UsersAdd", "Users", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    @class = "kt-form ajax-form",
    @id = "UsersAdd",
    showLoading = true,
    spellcheck = false
}))
{
    <div class="modal-header">
        <h1 class="modal-title">Thêm user</h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <label for="ids">Tìm user</label><label class="text-red error ml-5" for="ids"></label>
        <div class="usersAddContainer">
            <div class="usersAdd-element">
                <select class="form-control select-usersAdd" multiple="multiple"></select>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Hoàn tất</button>
    </div>
}

Digiticket.cms/Views/Users/Partial/_UsersEditModal.cshtml
@using DigiticketCMS.Models.Users;
@model UsersEditToViewModel

@using (Html.BeginForm("UsersEdit", "Users", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    @class = "kt-form ajax-form",
    showLoading = true,
    spellcheck = false
}))
{
    <div class="modal-header">
        <h1 class="modal-title">Update user <span class="text-success">@Model.Name</span></h1>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div id="UsersUpdateModalTree">
            <ul>
                @foreach (var item in Model.Data)
                {
                    <li data-jstree='{"opened": true,"selected": @(item.IsSelected ? "true" : "false")}' id="@item.Id">
                        <span>@item.Name</span>
                    </li>
                }
            </ul>
        </div>
        <input type="hidden" name="UserId" value="@Model.Id" />
        <input type="hidden" name="RoleIds" id="tree-values" value="@(String.Join("~", Model.Data.Where(u => u.IsSelected == true).Select(u => u.Id)))" />
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Hoàn tất</button>
    </div>
}