Digiticket.cms/Models/Tags/TagsViewModel.cs
using Services.Models;
using Services.Models.Responses.Lib;
using Services.Models.Responses.Product;
using Services.Models.Responses.Tags;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DigiticketCMS.Models.Tags
{
    public class TagsViewModel : BaseViewModel
    {
    }
    public class ProductTagsGetByPageViewModel : BaseViewModel
    {
        public int ParentId { get; set; }
        public string ParentName { get; set; }
        public string CategoryId { get; set; }
        public string DestinationId { get; set; }
        public int? Type { get; set; }   
        public ProductTagsGetByPageViewModel()
        {
            ParentId = 0;
            ParentName = "";
        }
    }
    public class ProductTagsAddModalViewModel
    {
        public string Keyfilter { get; set; }
        public int ParentId { get; set; }
        public string ParentName { get; set; }
        public string FilterName { get; set; }
        public string CategoryId { get; set; }
        public string DestinationId { get; set; }
        public string CategoryName { get; set; }
        public string DestinationName { get; set; }
        public int Type { get; set; }
        public List<SubCategoryResponse> Categories { get; set; }
        public List<LibDestinationResponse> Destinations { get; set; }
        public BaseResponse<PagingResult<ProductTagsResponse>> GetByPage { get; set; }
    }
    public class TagsAddModalViewModel
    {
        public int ParentId { get; set; }
        public string CategoryId { get; set; }
        public string DestinationId { get; set; }
        public string CategoryName { get; set; }
        public string DestinationName { get; set; }
        public string ParentName { get; set; }
        public int Type { get; set; }

        public List<SubCategoryResponse> Categories { get; set; }
        public List<LibDestinationResponse> Destinations { get; set; }
    }
    public class ProductInfoToView
    {
        public List<SubCategoryResponse> Categories { get; set; }
        public List<LibDestinationResponse> Destinations { get; set; }
    }
    public class ProductTagsAddViewModel
    {
        public int ParentId { get; set; }
        [Required]
        public Guid CategoryId { get; set; }
        [Required]
        public Guid DestinationId { get; set; }
        [Required]
        public string Name { get; set; }
        public string TextView { get; set; }
        public string TextLink { get; set; }
        public int Type { get; set; }
        public int Idx { get; set; }
        public int TypeResponse { get; set; }
        public ProductTagsAddViewModel()
        {
            TypeResponse = 1;
        }
    }
    public class ProductTagsUpdateIdxViewModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public int Idx { get; set; }
    }
    //public class ProductTagsGetListViewModel
    //{
    //    [Required]
    //    public int parentId { get; set; }
    //    public string key { get; set; }
    //    [Required]
    //    public Guid categoryId { get; set; }
    //    [Required]
    //    public Guid destinationId { get; set; }
    //}
    //public class JustHasId
    //{
    //    public int id { get; set; }
    //    public int idx { get; set; }
    //    public string name { get; set; }
    //}
}

Digiticket.cms/Controllers/TagsController.cs
using AutoMapper;
using DigiticketCMS.Config;
using DigiticketCMS.Helpers;
using DigiticketCMS.Models;
using DigiticketCMS.Models.Tags;
using DigiticketCMS.Services.Models;
using Infrastructure.Config;
using Infrastructure.Extensions;
using Newtonsoft.Json;
using Services.Interfaces;
using Services.Models.Requests.Tags;
using Services.Models.Responses.Tags;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Utilities.Caching;

namespace DigiticketCMS.Controllers
{
    [Authorize]
    public class TagsController : BaseController
    {
        #region constructor
        private ITagsServices _tagsServices;
        private ILibServices _libServices;
        public TagsController(ITagsServices tagsServices,
                              ILibServices libServices)
        {
            _tagsServices = tagsServices;
            _libServices = libServices;
        }
        #endregion

        #region get by page
        public ActionResult Tags(ProductTagsAddModalViewModel model)
        {
            if (User.CheckPermission(Permission.Tags))
            {
                model.Categories = _libServices.CategoryGetAll(User.Identity.GetClaims("token")).Data;
                model.Destinations = _libServices.DestinationGetAll(User.Identity.GetClaims("token")).Data;
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }

        public JsonResult TagsGetByPage(ProductTagsGetByPageViewModel model)
        {
            if (User.CheckPermission(Permission.TagsView))
            {
                if (model.key == null) model.key = "";
                if (model.key.CheckForKey())
                {
                    var request = Mapper.Map<ProductTagsGetByPageRequest>(model);
                    request.PageIndex = model.page;
                    request.PageSize = model.perpage;
                    request.FieldName = model.field;
                    request.Orderby = model.sort;
                    request.Filter = new List<FilterRequest>();

                    if (!string.IsNullOrEmpty(model.CategoryId) && model.CategoryId != "null")
                    {
                        request.Filter.Add(new FilterRequest()
                        {
                            Opt = FilterOptionOpt.AND,
                            Name = "categoryId",
                            Opt1 = FilterOptionOpt1.EqualTo,
                            Type = FilterOptionType.String,
                            Values = model.CategoryId
                        });
                    }
                    if (model.DestinationId.IsTrueOrFalse())
                    {
                        request.Filter.Add(new FilterRequest()
                        {
                            Opt = FilterOptionOpt.AND,
                            Name = "destinationId",
                            Opt1 = FilterOptionOpt1.EqualTo,
                            Type = FilterOptionType.String,
                            Values = model.DestinationId
                        });
                    }
                    if (model.Type != null)
                    {
                        request.Filter.Add(new FilterRequest()
                        {
                            Opt = FilterOptionOpt.AND,
                            Name = "type",
                            Opt1 = FilterOptionOpt1.EqualTo,
                            Type = FilterOptionType.Number,
                            Values = model.Type.ToString()
                        });
                    }
                    request.Filter.Add(new FilterRequest()
                    {
                        Opt = FilterOptionOpt.AND,
                        Name = "parentId",
                        Opt1 = FilterOptionOpt1.EqualTo,
                        Type = FilterOptionType.Number,
                        Values = model.ParentId.ToString()
                    });
                    if (!string.IsNullOrEmpty(model.key))
                    {
                        request.Keyword = model.key;
                    }
                    var result = _tagsServices.GetByPage(request, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        long totalItems = result.Data.Total;
                        var totalPages = Math.Ceiling((double)totalItems / model.perpage);
                        return Json(new JsonDataTable
                        {
                            meta = new PagingInfo
                            {
                                page = model.page,
                                pages = (long)totalPages,
                                perpage = model.perpage,
                                total = totalItems,
                                field = model.field
                            },
                            data = result.Data.Result
                        }, JsonRequestBehavior.AllowGet);
                    }
                    else if (result.Code == 401)
                    {
                        Response.Cookies[SystemConfig.System_AuthCookieName].Value = string.Empty;
                        Response.Cookies[SystemConfig.System_AuthCookieName].Expires = DateTime.Now.AddMonths(-1);
                        return Json(new
                        {
                            page = "login page"
                        }, JsonRequestBehavior.AllowGet);
                    }
                }
                return Json(new JsonDataTable
                {
                    meta = new PagingInfo()
                    {
                        page = model.page,
                        perpage = model.perpage,
                    },
                    data = new List<ProductTagsResponse>()
                }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonDataTable
            {
                meta = null,
                data = null
            }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region add
        [HttpGet]
        public ActionResult TagsAddModal(TagsAddModalViewModel model)
        {
            if (User.CheckPermission(Permission.TagsAdd))
            {
                if (string.IsNullOrEmpty(model.DestinationId) && string.IsNullOrEmpty(model.CategoryId))
                {
                    model.Categories = _libServices.CategoryGetAll(User.Identity.GetClaims("token")).Data;
                    model.Destinations = _libServices.DestinationGetAll(User.Identity.GetClaims("token")).Data;
                    return PartialView("Partial/_TagsAddModal", model);
                }
                return PartialView("Partial/_TagsAddModal", model);
            }
            return PartialView("~/Views/Shared/_ErrorViewModal.cshtml", new ErrorViewModel()
            {
                Title = "You do not have permission!",
            });
        }

        [HttpPost]
        public JsonResult Add(ProductTagsAddViewModel model)
        {
            if (User.CheckPermission(Permission.TagsAdd))
            {
                if (ModelState.IsValid)
                {
                    var request = Mapper.Map<ProductTagsAddRequest>(model);
                    var result = _tagsServices.Add(request, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        var keyToken = CacheNameConfig.GroupServiceTags;
                        CacheUtility.Delete(keyToken);
                        var infoTagJustAdded_JSON = new ProductTagsForViewResponse();
                        if (model.TypeResponse == 2 || model.TypeResponse == 3)
                        {
                            var infoTagJustAdded = _tagsServices.GetById(result.Data, User.Identity.GetClaims("token"));
                            if (infoTagJustAdded.IsOK() && infoTagJustAdded.Data != null)
                            {
                                infoTagJustAdded_JSON = Mapper.Map<ProductTagsForViewResponse>(infoTagJustAdded.Data);
                                infoTagJustAdded_JSON.TypeResponse = model.TypeResponse;
                            }
                        }
                        return Json(new JsonClientResult
                        {
                            Success = true,
                            CallBack = $"TagsGetByPage.onRendAfterUpdate('Thêm mới thành công', `{JsonConvert.SerializeObject(infoTagJustAdded_JSON)}`);",
                        });
                    }
                    return Json(new JsonClientResult
                    {
                        CallBack = result.Errors.CB_UpdateErrorResult()
                    });
                }
                return Json(new JsonClientResult
                {
                    CallBack = $"Common.onError(`{GetModelStateError()}`);"
                });
            }
            return Json(new JsonClientResult
            {
                CallBack = $"Common.onError(`You do not have permission`);"
            });
        }

        [HttpPost]
        public JsonResult AddTagReturnPartial(ProductTagsAddViewModel model)
        {
            if (User.CheckPermission(Permission.TagsAdd))
            {
                if (ModelState.IsValid)
                {
                    var request = Mapper.Map<ProductTagsAddRequest>(model);
                    var result = _tagsServices.Add(request, User.Identity.GetClaims("token"));
                    if (result.IsOK())
                    {
                        var keyToken = CacheNameConfig.GroupServiceTags;
                        CacheUtility.Delete(keyToken);
                       
                        
                    }
                    return Json(new JsonClientResult
                    {
                        CallBack = result.Errors.CB_UpdateErrorResult()
                    });
                }

Digiticket.cms/Views/Tags/Partial/_ProductTagsSuggest.cshtml
@using Infrastructure.Extensions;
@using Services.Models.Responses.Tags;
@model List<ProductTagsResponse>

<ul class="list-suggest-tags mt-2" style="padding-inline-start:1rem">
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <li class="pointer mt-2 template"
                data-id="@item.Id"
                data-parentId="@item.ParentId"
                data-categoryId="@item.CategoryId"
                data-destinationId="@item.DestinationId"
                data-textView="@item.TextView"
                data-textLink="@item.TextLink"
                data-name="@item.Name"
                data-type="@item.Type"
                data-idx="@item.Idx">
                @item.Name @(item.ParentName != null && item.ParentName != "" ? $"(parent: {item.ParentName} )" : "")
            </li>
        }
    }
    else
    {
        <li class="mt-2">Không có kết quả</li>
    }
</ul>

Digiticket.cms/Views/Tags/Partial/_TagsAddModal.cshtml
@using DigiticketCMS.Models.Tags;
@using Infrastructure.Extensions;
@using DigiticketCMS.Helpers;
@using DigiticketCMS.Config;
@model TagsAddModalViewModel

@using (Html.BeginForm("Add", "Tags", FormMethod.Post, new
{
    enctype = "multipart/form-data",
    @class = "kt-form ajax-form",
    @id = "TagsAdd",
    spellcheck = false
}))
{
    <input type="hidden" value="@Model.ParentId" name="parentId" readonly />
    <div class="modal-header">
        @if (Model.ParentId == 0)
        {
            <h1 class="modal-title">Thêm mới parent Tags</h1>
        }
        else
        {
            <h1 class="modal-title">
                Thêm mới sub tags
                @if (!string.IsNullOrEmpty(Model.ParentName) && Model.ParentName != "null")
                {
                    <span>| </span><span class="text-success"> parent: @Model.ParentName</span>
                }
            </h1>
            <input type="hidden" value="@Model.CategoryId" name="categoryId" />
            <input type="hidden" value="@Model.DestinationId" name="destinationId" />
        }
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="mt-4">
            <label>Chọn danh mục</label><label class="text-red error ml-5" for="categoryId"></label>
            @if (string.IsNullOrEmpty(Model.CategoryId))
            {
                <select class="cursor-pointer form-control kt-select2-category--modal" name="categoryId">
                    <option value="00000000-0000-0000-0000-000000000000">Không chọn</option>
                    @if (!Model.Categories.IsNullOrEmpty())
                    {
                        foreach (var category in Model.Categories)
                        {
                            <optgroup label="@category.Name">
                                @foreach (var subCategory in category.SubCategory)
                                {
                                    <option value="@subCategory.Id">@subCategory.Name</option>
                                }
                            </optgroup>
                        }
                    }
                </select>
            }
            else
            {
                <select class="cursor-pointer form-control kt-select2-category--modal--disable" name="categoryId">
                    <option value="@Model.CategoryId">@(Model.CategoryName.IsTrueOrFalse() ? Model.CategoryName : "Không có")</option>
                </select>
            }
        </div>
        <div class="mt-4">
            <label>Chọn điểm đến</label><label class="text-red error ml-5" for="destinationId"></label>
            @if (string.IsNullOrEmpty(Model.DestinationId))
            {
                <select class="form-control kt-select2-destination--modal cursor-pointer" name="destinationId">
                    <option value="00000000-0000-0000-0000-000000000000">Không chọn</option>
                    @if (!Model.Destinations.IsNullOrEmpty())
                    {
                        foreach (var destination in Model.Destinations)
                        {
                            <option value="@destination.Id">@destination.Name</option>
                        }
                    }
                </select>
            }
            else
            {
                <select class="form-control kt-select2-destination--modal--disable cursor-pointer" name="destinationId">
                    <option value="@Model.DestinationId">@(Model.DestinationName.IsTrueOrFalse() ? Model.DestinationName : "Không có")</option>
                </select>
            }
        </div>
        <div class="mt-4">
            <label for="name">Tên</label><label class="text-red error ml-5" for="name"></label>
            <input type="text" class="form-control" name="name" id="name" />
        </div>
        <div class="mt-4">
            <label for="textView">Ký tự hiển thị</label><label class="text-red error ml-5" for="textView"></label>
            <input type="text" class="form-control" name="textView" id="textView" />
        </div>
        <input type="hidden" class="form-control" name="textLink" readonly />
        <div class="mt-4">
            <label for="type">Loại</label>
            @if(Model.ParentId != 0)
                {
                    <input type="hidden" name="type" value="@Model.Type" />
                }
            <select class="form-control cursor-pointer @(Model.ParentId != 0 ? "kt-select2-type--modal--disable" : "")" name="type">
                <option value="0" @(Model.Type == 0)>Không chọn</option>
                <option value="@((int)EnumCommonCode.ETagsItemType.Product)" @((int)EnumCommonCode.ETagsItemType.Product == Model.Type ? "selected" : "")>
                    @EnumCommonCode.GetDisplayNameEnum(EnumCommonCode.ETagsItemType.Product)
                </option>
                <option value="@((int)EnumCommonCode.ETagsItemType.GroupService)" @((int)EnumCommonCode.ETagsItemType.GroupService == Model.Type ? "selected" : "")>
                    @EnumCommonCode.GetDisplayNameEnum(EnumCommonCode.ETagsItemType.GroupService)
                </option>
                <option value="@((int)EnumCommonCode.ETagsItemType.GroupServiceProcess)" @((int)EnumCommonCode.ETagsItemType.GroupServiceProcess == Model.Type ? "selected" : "")>
                    @EnumCommonCode.GetDisplayNameEnum(EnumCommonCode.ETagsItemType.GroupServiceProcess)
                </option>
                <option value="@((int)EnumCommonCode.ETagsItemType.ProductHighlight)" @((int)EnumCommonCode.ETagsItemType.ProductHighlight == Model.Type ? "selected" : "")>
                    @EnumCommonCode.GetDisplayNameEnum(EnumCommonCode.ETagsItemType.ProductHighlight)
                </option>
                <option value="@((int)EnumCommonCode.ETagsItemType.GroupServiceView)" @((int)EnumCommonCode.ETagsItemType.GroupServiceView == Model.Type ? "selected" : "")>
                    @EnumCommonCode.GetDisplayNameEnum(EnumCommonCode.ETagsItemType.GroupServiceView)
                </option>
            </select>
        </div>
        <div class="mt-4">
            <label for="idx">Index</label><label class="text-red error ml-5" for="idx"></label>
            <input min="0" type="number" class="form-control" name="idx" value="0" />
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Hoàn tất</button>
    </div>
}